### PR TITLE
docker-compose: bump version to 3

### PR DESCRIPTION
**Pull request by simar7**
Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by simar7** [comment]
hmm weird, not sure why the other already merged commits are showing up here.

**Comment by waltzofpearls** [comment]
git rebase?

**Comment by simar7** [comment]
I think it has to do with the fact that the previous commit that was merged on master of the upstream branch was squashed into one and this PR includes them as separate commits. There's no change if you see the diff now after I rebased.

**Comment by simar7** [comment]
Um, something has terribly gone wrong. I'll recreate this PR.

**Pull request closed without merging**
